// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLBbKd2dhtSZ2dAmFcoTP5_ZXwr9bkE0',
    appId: '1:855899288121:web:815d851a72f7bdf75b53e8',
    messagingSenderId: '855899288121',
    projectId: 'ethiochat-backend-d23d6',
    authDomain: 'ethiochat-backend-d23d6.firebaseapp.com',
    storageBucket: 'ethiochat-backend-d23d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBx1jrRHjI5hX1nX-AKMuP65tqXF5SYl0',
    appId: '1:855899288121:android:793df491d9fe2c7c5b53e8',
    messagingSenderId: '855899288121',
    projectId: 'ethiochat-backend-d23d6',
    storageBucket: 'ethiochat-backend-d23d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgSLIdRALsG98LOKUovAE-brsD27fzcJI',
    appId: '1:855899288121:ios:f357ad9c96354c515b53e8',
    messagingSenderId: '855899288121',
    projectId: 'ethiochat-backend-d23d6',
    storageBucket: 'ethiochat-backend-d23d6.appspot.com',
    iosBundleId: 'com.example.ethiochat',
  );
}
